version: '2'
services:
  zones:
    build:
      context: .
      dockerfile: app/zones/Dockerfile
    command: [ "--config", "/config/docker.yml" ]
    volumes:
      - ./config:/config:ro # configuration files
      - ${SSH_DIR}:/ssh:ro  # ssh keys
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - ./db:/docker-entrypoint-initdb.d      # initialization scripts, only executed first time
      - ${DB_VOLUME}:/var/lib/postgresql/data # persistent storage of database
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
