package czds

import (
	"errors"
	"github.com/aau-network-security/go-domains/zone"
	"github.com/rs/zerolog/log"
	"os"
	"testing"
)

func TestCzds(t *testing.T) {
	zone.SkipCI(t)

	user := os.Getenv("CZDS_USER")
	pass := os.Getenv("CZDS_PASS")
	conf := Credentials{
		Username: user,
		Password: pass,
	}
	z := New(conf, "net")

	count := 0
	f := func(domain []byte) error {
		log.Debug().Msgf("%s", domain)
		count++
		return errors.New("error generated by test")
	}

	opts := zone.ProcessOpts{
		DomainFn:       f,
		StreamWrappers: []zone.StreamWrapper{zone.GzipWrapper},
		StreamHandler:  zone.ZoneFileHandler,
	}

	if err := zone.Process(z, opts); err != nil && count != 1 {
		t.Fatalf("error while processing zone: %s", err)
	}

}
