com:
  ftp:
    tld: com
    host: rz.verisign-grs.com
    username: <username>
    file: com.zone.gz
  ssh:
    host: <host for SSH proxy>
    user: <user>
    authtype: key
    key: <path to key>
czds:
  tlds:
    - xyz
  credentials:
    username: <username>
dk:
  http:
    tld: dk
    url: <url>
  ssh:
    host: <host for SSH proxy>
    user: <username>
    authtype: password
store:
  host: localhost
  port: 10001
  user: postgres
  password: postgres
  dbname: domains
