time-window:
  # format: <yyyy-mm-dd>
  active: <true | false>
  start: <day to start from>
  end: <day to end at>
worker_count: <number of workers to use>
api-address:
  secure: <true | false>
  host: <host>
  port: <port>
meta:
  host: <host that runs measurement, for meta info storage purposes>
  description: <description of measurement>
all: <true | false>
included:
  - <URL of a single CT log>
excluded:
  - <URL of a single CT log>