com:
  enabled: <true | false>
  ftp:
    tld: com
    host: rz.verisign-grs.com
    username: <username>
    file: com.zone.gz
  ssh-enabled: <true | false>
  ssh:
    host: <host for SSH proxy>
    user: <user>
    authtype: key
    key: <path to key>
czds:
  enabled: <true | false>
  all: <true | false> # set true to use czds api to find all tlds that can be accessed
  included: # list of tlds to include
    - a
    - b
  excluded: # list of tlds to exclude
    - c
    - d
  credentials:
    username: <username>
dk:
  enabled: <true | false>
  http:
    tld: dk
    url: <url>
  ssh:
    host: <host for SSH proxy>
    user: <username>
    authtype: password
api-address:
  secure: <true | false>
  host: <host>
  port: <port>
meta:
  host: <host that runs measurement, for meta info storage purposes>
  description: <description of measurement>